* Akash Supercloud

#+FILETAGS: :akash:DePIN:web3:AWS:AI:cloud:

** Overview notes

1. The purpose of Akash supercloud is to provide decentralized and
   affordable and permissionless compute
2. Users have the freedom to select resources at the prices they
   are willing to pay
3. The significance of Akash achieving IBC communication with Cosmos
   enables it to achieve seamless communication with other chains in
   the Cosmos ecosystem
4. Using Akash's orchestration layer powered by SDL allows intricate
   application deployment setups in the Akash cloud
5. The text-to-image model from Stability AI deployed on Akash is
   called AkashGen

** Akash comparison to traditional cloud providers               :comparison:

1. The main goal of Akash as described is to serve as a decentralized
   marketplace where providers match with tenants efficiently and
   effectively.
2. Differences between the Akash Network and traditional cloud service
   models like AWS:
   - The Akash network is distributed whereas traditional cloud providers
     are limited to specific regions
   - Resources in Akash are provided on demand whereas traditional
     cloud providers may require lengthy contracts in some cases
   - The Akash network is standardized using open source technologies
     whereas traditional cloud vendors provide custom interfaces and
     services that subject users to vendor lock-in
3. The key components of Akash are:
   a) The providers who run kubernetes clusters and sell infrastructure
   b) The tenants who purchase resources to run their containerized
      applications
   c) The Akash network that provides a standardized marketplace that
      connects providers and tenants
4. Challenges of existing decentralized compute setups that Akash
   intends to solve include underutilization of infrastructure,
   non-standardized deployment processes across multiple infra owners
   and lack of an on demand marketplace.
5. Benefits Akash tenants gain include cost effective prices,
   standardized access to resources (no vendor lock-in), open source
   community participation in the network.

** AKT Token                                                          :token:

1. The primary function of the AKT token is to support the development and
   operation of the Akash network the following ways:
   - Governance :: Holders of AKT vote on proposals
   - Security :: The Akash network is secured via PoS
   - Store of Value :: The means via which value is stored and exchanged on the network

2. Staking contributes to the security of the network by allowing
   validators to secure the network through PoS.

3. Some key features of AKT 2.0 are:
   - allowing funding of specialized pools
   - providing a wide range of currency options for lease settlement

4. AKT tokens can be bought from centralized exchanges like Coinbase
   and Kraken and decentralized exchanges like Osmosis

5. Providers are required to stake AKT as collateral to participate in
   the marketplace. This incentivizes them to offer reliable services
   because they have vested interest in its success.

** Community                                                      :community:

1. The main purpose of the community is to contribute to development
   of the Akash network and help shape the future of Akash
2. Users can become part of the Insiders program by applying
3. Contributions that build the network are eligible for financial
   rewards
4. The Akash EDU program helps developers master cloud computing on
   Akash
5. Benefits of joining the Akash network community include getting to
   shape Akash through code and culture

*** Akash Validators                                   :validators:sig:chain:

1. An Akash Network Validator helps keep the blockchain running
   reliably by validating transactions, securing the network and
   participating in governance.
2. To become a validator, one needs to stake AKT, and have the
   necessary hardware and connectivity to participate in the network
   consensus
3. Validators contribute to the security of the Akash Network by
   committing valid transactions and preventing issues like double-spend
   through consensus
4. Validators who engage in malicious activities or network disruptions
   are penalized.
5. Akash Network Validators are rewarded via AKT for their participation

**** Validator Nodes

- Verify transactions included in a block
- Propagate blocks to other nodes
- Participate in concensus via the tendermint based PoS algo
- Take part in governance by voting on proposals to modify network
  params, upgrades to protocl and community funds

** Development

*** open source contributions                                   :open_source:

1. The 3 types of community groups in the Akash Network are:

   - Special Interest Groups (SIGs) :: These are vertically specialized
     persistent groups working on foundational aspects of the Akash
     Network
   - Working Groups (WGs) :: These are horizontally aligned groups that
     work on cross cutting concerns that involve multiple SIGs. They are
     typically time-limited and define high level requirements that are
     further refined by SIGs
   - Committees :: These are groups that handle sensitive topic for
     which some level of discretion and confidentiality may be involved,
     although as much openess as possible is encouraged e.g. security,
     code of conduct etc

2. The Steering Committee's role is to evaluate projects and define
   priorities and decide which SIGs and WGs tackle specific tasks.

3. Contributions in form of writing code, docs, testing and more are
   welcome.

Links:
 - [[https://github.com/orgs/akash-network/projects][List of Projects]]
 - [[https://github.com/orgs/akash-network/discussions/811][Akash Contributions Program]]

*** Product Strategy                                                :product:

1. Akash's long-term goal is to become a viable alternative to centralized
   public clouds.

2. Primary themes guiding Akash's product development in the short term are:
   - Node operators :: RPC, validation nodes
   - Web hosting :: alternatives to services like Vercel
   - AI/ML applications :: Inference and fine-tuning

3. Akash plans to achieve Cloud Parity by providing foundational
   infrastructure like compute and partnering with third parties
   to provide managed services.

4. Akash is specifically targeting the following use-cases:
   - Node deployments
   - AI/ML workloads
   - Web/Application hosting

5. Akash's execution framework borrows from the Kubernetes project:
   - Different community groups working on projects (WGs, SIGs)
   - A prioritized pipeline of projects/ideas to be built in [[https://akash.network/development/current-projects/#list-of-projects][project list]]
   - Documented places to discuss/publish/comment/review/approve specifications
     for each project
   - States a given project can be in
   - Regular documented meetings to discuss progress of projects

*** Funding Programs                                                :funding:

**** Contributions program

AKT funding available for small contributions helping build and
progress the network through the Community Support Governance
Proposals managed by Overclock labs.

[[https://github.com/orgs/akash-network/discussions/811][Application]]

**** Community Pool Spend Proposals

Permissionless and managed by the community, anyone can [[https://www.mintscan.io/akash/address/community-pool][request funds]].

Must pass on-chain governance.

[[https://github.com/orgs/akash-network/discussions/170][Best Practices]]

**** Delegations

Earned and maintained over time by consistent, professional,
value-adding contributions.

**** Overclock labs based Grants

Has funds available for projects and teams that align with the Akash
Network goals

** Bids and Leases                                              :bids:leases:

*** Users

 - Tenants
 - Providers

*** Reverse Auction
 - tenants create orders
 - providers bid on orders
 - tenant chooses winning bid

*** Deposits and Payments :escrow:escrow_accounts:payments:settlement:accounting:

- Tenants deposit AKT on placing an order min 0.5akt
- Providers deposit AKT on placing a bid

**** Escrow Accounts

A mechanism for time-based payments between accounts without block by
block micropayments.

Necessary because:
 - Although leases are priced in blocks, performance and security
   considerations prevent payments from being made by the block
 - Bidding should not be free for performance and security reasons.
   Funds are held in an escrow account and returned to bidder when bid
   is closed.

Deposits are made to escrow accounts and can be topped up.

Payments represent transfers from Escrow account to another account.

**** Account settlement

This is updating the internal accounting of an escrow account to the
current block height.

Process:

1. Determine blockRate - the amount owed for every block.
2. Determine heightDelta - the number of blocks since last settlement.
3. Determine numFullBlocks - the number of blocks that can be paid for in full.
4. Transfer amount for numFullBlocks to payments.
5. If numFullBlocks is less than heightDelta (account overdrawn), then
   1) Distribute remaining balance among payments, weighted by each payment’s rate
   2) Distribute any remaining balance from above as evenly as possible
   3) Set account and payments to state OVERDRAWN.
   
   
** DSEQ, GSEQ, OSEQ                                          :dseq:oseq:gseq:

*** GSEQ (Group Sequence)
Groups of containers in a deployment leased independently on a
specific provider

It is possible to create multiple leases to different providers in
a single deployment

*** DSEQ (Deployment Sequence)

Unique identifier assigned to each deployment on Akash

*** OSEQ (Order Sequence)

Distinguishes multiple orders associated with a single deployment.

It is possible to move a deployment between providers. This can be
done by by closing the lease and creating a new order while leaving
the deployment open.

The new order will have a new OSEQ associated with it and is referenced
in the bids.

** Stack Definition Language (SDL)                                      :sdl:

*** Services                                                       :services:

Defines workloads to be run on an Akash deployment.

Includes the docker image, env variables, exposed ports etc

*** Profiles                                                       :profiles:

**** Compute                                                        :compute:

Defines a mapping of named profiles to compute resources like cpu,
gpu, memory, storage.

**** Placement

Defines named datacenter profiles which describe required attributes,
signoffs and max prices per block for the compute profiles.

*** Deployment

Describes how to deploy the services. Maps each service to a
datacenter and compute profile.

** Archtecture overview

Composed of 4 layers:

*** Blockchain Layer
This is the distributed consensus mechanism that maintains the
  distributed ledger, validator management, governance and token
  transactions

Built on:

- Tendermint Core :: The Byzantine Fault Tolerant consensus engine
- Cosmos SDK :: Framework that allows the creation of custom blockchains

*** Application Layer

- Manages the application lifecycle on the Akash network:
  - User makes Deployment
  - User makes an order
  - Providers place bids for orders
  - Lease created between user and provider once user selects bid
  - Deployment closed once lease is terminated

*** Provider Layer    

The ecosystem of datacenters, cloud providers and server operators that
provide their resources to the Akash Network.

Components:

- Provider Daemon :: software that does resource allocation and
  communicates to the blockchain
- Container Orchestration :: manages the deployment and scaling
  of user applications.

*** User Layer

These are the developers or businesses that use the Akash Network
to run their applications.

They use the following interfaces:

- The Akash CLI
- The Akash Console
