#+FILETAGS: :fastai:

* Areas where deep learning is now the best in the world
 - Computer Vision :: self-driving cars, face recognition
 - NLP :: surmarizing documents, chatbots e.g. openGPT
 - Medicine :: finding anomalies in radiology images
 - Image Generation :: Colourizing images, stable diffusion
 - Games :: Chess, Go
 - Biology :: Protein folding
 - Recommendation systems :: movies, shopping, search

* Artificial Neural Networks         :ann:artificial_neural_networks:history:
The first device based on the principle of the artifician neuron was
the Mark 1 Perceptron. It was designed for image recognition, with
20 * 20 photocells connected to weights.

* Parallel Distributed Processing requirements
Based on the 1986 book MIT press

 - A set of processing units
 - Interconnection between the processing units
 - A state of activation
 - An output function for each unit
 - A propagation rule for propagating patterns of activities through the network
 - An activation rule combining inputs to a unit with the current
   state of the unit to give an output from the unit
 - A learning rule where patterns of connectivity are modified by
   experience
 - An environment within which the system must operate

* Misunderstandings that held back the field of neural networks
 - That they were incapable of learning some simple mathematical functions like XOR

* GPU
A graphics processing unit is a specialized computer processor that executes
a computer instruction in parallel on many data points.

* Image recognition using traditional computer programs

It is hard to recognize images using traditional computer programs
because traditional programming works by specifying a step by step
procedure expressed in detail.

It is extremely hard to write a step by step procedure to instruct a
computer to recognize an image, let along generalize it.

Machine learning by Arthur Samuel (1949)

By weight assignment, Samuel meant values assigned to variables which
affected how his program made decisions.

In deep learning, we use parameters in place of what Samuel called
weights. A weight is a specific type of parameter in deep learning.

** Samuel's view of the machine learning model

| Source      | Action         | Destination/Output |
|-------------+----------------+--------------------|
| Inputs      | provided to    | Model              |
| Weights     | provided to    | Model              |
| Model       | produces       | Results            |
| Results     | evaluated into | Performance        |
| Performance | updates        | Weights            |

In his view the process of updating weights to optimize performance
could be made automatic.

Why is it hard to understand why a deep learning model makes a particular prediction?

What is the name of the theorem that shows that a neural network can solve any mathematical problem to any level of accuracy?

What do you need in order to train a model?

How could a feedback loop impact the rollout of a predictive policing model?

Do we always have to use 224×224-pixel images with the cat recognition model?

What is the difference between classification and regression?

What is a validation set? What is a test set? Why do we need them?

What will fastai do if you don't provide a validation set?

Can we always use a random sample for a validation set? Why or why not?

What is overfitting? Provide an example.

What is a metric? How does it differ from "loss"?

How can pretrained models help?

What is the "head" of a model?

What kinds of features do the early layers of a CNN find? How about the later layers?

Are image models only useful for photos?

What is an "architecture"?

What is segmentation?

What is y_range used for? When do we need it?

What are "hyperparameters"?

What's the best way to avoid failures when using AI in an organization?
