* On experience vs competence in organizations :corporations:competence:experience:institutions:

Corporations hate non quantifiable because you cannot create process
with it and most companies cannot execute things that cannot be stated
as fully quantifiable process. You can improve almost everything by
allowing non-quantifiables to factor in.

https://twitter.com/tobi/status/1607829493250658304

* Find nth fibonacci number                                       :fibonacci:

https://github.com/programmer-ke/codings/blob/master/py/nth_fibonacci.py

* Build small skills in right order :learning:public_speaking:toastmasters:scientology:

https://www.lesswrong.com/posts/qwdupkFd6kmeZHYXy/build-small-skills-in-the-right-order

* swaks                                           :email:email_testing:swaks:

Email testing tool: http://www.jetmore.org/john/code/swaks/

* dpkg download and extract deb file                           :dpkg:apt:deb:

apt-get download <package_name> - downloads it

dpkg-deb -c package.deb - list contents

dpkg-deb -x package.deb destination_dir - extract contents to destination_dir

* ClamAV daemon using too much memory            :clamav:clamd:oom:antivirus:

Could be due to concurrent DB reload

https://betatim.github.io/posts/clamav-memory-usage/

* Elon Musk's 5 step process              :management:elon_musk:corporations:

 1) Work hard to make requirements less wrong
 2) Simplify - remove unnecessary parts
 3) Optimize
 4) Automate

https://www.linkedin.com/pulse/5-step-process-elon-musk-used-grow-tesla-spacex-paul-knight/

* New theory of management :management:elon_musk:corporations:institutions:geohot:

By continually creating chaos, process is incapable of forming, and
everyone is forced to work only toward goal.

https://geohot.github.io/blog/jekyll/update/2022/12/31/eacc.html

* npm install ERR! ENOTEMPTY                              :npm:err:enotempty:

https://github.com/npm/cli/issues/4096

* Data leakage :data_leakage:machine_learning:ml:train_test_contamination:target_leakage:

 - target leakage :: when using historical data to train a model,
   accidentally including an attribute that is dependent on the target
   variable in training e.g. when predicting house price based on its
   attributes, including average house prices in the locality
 - train test contamination :: accidentally including data that is
   available in the test set when training which will make the model
   overfit the test data.
   
* Spoof mail as authenticated user                    :sasl:spoof:smtp:swaks:

Using swaks to spoof mail as an authenticated user

swaks --from spoofedsender@domain --to recipient@domain --auth PLAIN --auth-user authenticateduser@domain --auth-password authenticatedpasswd --server smtp.domain.tld --tls

* purge snapd                                             :snap:purge:ubuntu:

https://web.archive.org/web/20200430055648/https://www.kevin-custer.com/blog/disabling-snaps-in-ubuntu-20-04/
https://askubuntu.com/questions/1251809/can-i-completely-remove-snappy-packages-from-ubuntu-20-04-without-affecting-the
